### ISSUE TITLE
codedeploy_role should output also role_id

### ISSUE THREAD

**Issue by holyjak** [skyscrapers/terraform-iam#11]
Currently it outputs `role_arn ` but e.g. https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html uses the role id (see https://www.terraform.io/docs/providers/aws/d/iam_role.html).

Thank you!

**Comment by iuriaranda** [comment]
@holyjak sorry for the late reply, and thank you for your contribution.

I've added two extra outputs in the module, which map the exact same attributes in the [`aws_iam_role` Terraform resource](https://www.terraform.io/docs/providers/aws/r/iam_role.html#attributes-reference):
* [`role_name`]: String: The name of the role.
* [`role_unique_id`]: String: The stable and unique string identifying the role.
