### ISSUE TITLE
Can you please give permission for `cloudwatch:GetMetricData`

### ISSUE THREAD

**Issue by rspljignesh** [skyscrapers/terraform-iam#19]
https://github.com/skyscrapers/terraform-iam/blob/92f86c08fe099c688db5b28ebf49dc8dd7671dee/cloudwatch_monitoring_role/main.tf#L4

Here its require for Latest Grafana Instance as now after 6.5.0 Grafana release they are fetching cloudwatch data with above permission.  Here is release document for reference. https://community.grafana.com/t/release-notes-v6-5-x/22704

**Comment by iuriaranda** [comment]
@rspljignesh thanks for reaching out. But I'm afraid I don't really understand your request.

The `cloudwatch_monitoring_role` you link above is meant to be attached to EC2 instances to **send** metric data to CloudWatch, not to retrieve it. And afaik it's not used for the purpose you mention with Grafana.

Can you clarify your question / request?

**Comment by rspljignesh** [comment]
Acctually here we are creating Instance Profile role with this module, and we are assigning that role to EC2 nodes, which is part of our Kunernetes Cluster. and on that kubernetes cluster we are deploying grafana application. So till date its working fine with `GetMetricsStatistics` access right, but recently after 6.5.0 they are using fetching cloudwatch data through `GetMetricsData` . Thats why we  need to enable that access.

**Comment by iuriaranda** [comment]
I see. As I mentioned, the `cloudwatch_monitoring_role` module only purpose is to give an IAM role permissions to send metrics to CloudWatch, so the permissions you propose don't really fit in there.

I suggest a couple of options for your use case:

- Add an extra policy to your IAM role with the permissions you need.
- Use something like [`kube2iam`](https://github.com/jtblin/kube2iam) to give fine-grained permissions to your Pods individually, without the need to give wide-range access to all your instances. With that you could attach an IAM role to your Grafana Pod with the exact permissions you need.

**Comment by rspljignesh** [comment]
Thanks for your reply, I have forked this repo to my organisation and made changes locally and prepared new release.

Thanks

**Comment by iuriaranda** [comment]
Ok, thanks to let us know. Feel free to share any feedback you may have on our modules, we'll be very glad to help out.

I'm going to go ahead and close this issue and the PR for now.
